import { resolveDashboardPath, type UserRole } from '@/hooks/useAuth'

export const dashboardPaths = {
  home: '/dashboard',
  student: '/dashboard/student',
  studentCourses: '/dashboard/student/courses',
  studentCourseDetail: (id: number) => `/dashboard/student/courses/${id}`,
  studentLesson: (courseId: number, lessonId: number) => `/dashboard/student/courses/${courseId}/lessons/${lessonId}`,
  studentCatalog: '/dashboard/student/catalog',
  studentProgress: '/dashboard/student/progress',
  studentQuiz: '/dashboard/student/quiz',
  studentAssignments: '/dashboard/student/assignments',
  studentCertificates: '/dashboard/student/certificates',
  studentCalendar: '/dashboard/student/calendar',
  studentMessages: '/dashboard/student/messages',
  studentGrades: '/dashboard/student/grades',
  studentNotifications: '/dashboard/student/notifications',
  studentProfile: '/dashboard/student/profile',
  studentHelp: '/dashboard/student/help',
  instructor: '/dashboard/instructor',
  instructorCourses: '/dashboard/instructor/courses',
  instructorStudents: '/dashboard/instructor/students',
  instructorCalendar: '/dashboard/instructor/calendar',
  instructorQuiz: '/dashboard/instructor/quiz',
  instructorAssignments: '/dashboard/instructor/assignments',
  instructorStats: '/dashboard/instructor/stats',
  instructorMessages: '/dashboard/instructor/messages',
  instructorNotifications: '/dashboard/instructor/notifications',
  instructorProfile: '/dashboard/instructor/profile',
  instructorHelp: '/dashboard/instructor/help',
  admin: '/dashboard/admin',
  adminUsers: '/dashboard/admin/users',
  adminModeration: '/dashboard/admin/moderation',
  adminHealth: '/dashboard/admin/health',
  adminActivity: '/dashboard/admin/activity',
} as const

export const resolveRoleDashboardPath = (role: UserRole) => resolveDashboardPath(role)
